// prelude.h -- the C++ runtime that is embedded into every generated file
#pragma once

// Kept as a raw string so the transpiler is a single self-contained binary.
inline const char* PY_PRELUDE = R"PYRT(// ---- generated by py2cpp -------------------------------------------
#include <algorithm>
#include <cctype>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <optional>
#include <random>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <vector>

namespace py {

// ===================== exceptions =====================
struct Exception : std::runtime_error {
    using std::runtime_error::runtime_error;
};
struct ValueError : Exception { using Exception::Exception; };
struct TypeError : Exception { using Exception::Exception; };
struct IndexError : Exception { using Exception::Exception; };
struct KeyError : Exception { using Exception::Exception; };
struct ZeroDivisionError : Exception { using Exception::Exception; };
struct RuntimeError : Exception { using Exception::Exception; };
struct StopIteration : Exception { using Exception::Exception; };

inline constexpr long long NONE_LL = std::numeric_limits<long long>::min();

// ===================== None =====================
struct NoneType {};
inline constexpr NoneType None{};
inline std::string str(NoneType) { return "None"; }
inline std::string repr(NoneType) { return "None"; }
inline constexpr bool operator==(NoneType, NoneType) { return true; }
inline constexpr bool operator!=(NoneType, NoneType) { return false; }
inline constexpr bool to_bool(NoneType) { return false; }
inline constexpr bool same(NoneType, NoneType) { return true; }
inline constexpr bool different(NoneType, NoneType) { return false; }
template <class T, class U>
inline constexpr bool same(const T& a, const U& b) { return a == b; }
template <class T>
inline constexpr bool same(const T&, NoneType) { return false; }
template <class T>
inline constexpr bool same(NoneType, const T&) { return false; }

// ===================== str() / repr() =====================
std::string str(double v);

inline std::string str(bool v) { return v ? "True" : "False"; }
inline std::string str(const std::string& v) { return v; }
inline std::string str(const char* v) { return std::string(v); }
template <std::size_t N>
inline std::string str(const char (&v)[N]) { return std::string(v); }
inline std::string str(char v) { return std::string(1, v); }
inline std::string str(float v) { return str(static_cast<double>(v)); }

inline std::string str(double v) {
    if (std::isnan(v)) return "nan";
    if (std::isinf(v)) return v > 0 ? "inf" : "-inf";
    if (std::fabs(v) < 1e16 && v == std::trunc(v)) {
        return std::to_string(static_cast<long long>(v)) + ".0";
    }
    char buf[64];
    for (int prec = 1; prec <= 17; ++prec) {
        std::snprintf(buf, sizeof(buf), "%.*g", prec, v);
        if (std::strtod(buf, nullptr) == v) return std::string(buf);
    }
    std::snprintf(buf, sizeof(buf), "%.17g", v);
    return std::string(buf);
}

template <class T,
          class = std::enable_if_t<std::is_integral_v<T> && !std::is_same_v<T, bool> &&
                                   !std::is_same_v<T, char>>>
inline std::string str(T v) {
    return std::to_string(v);
}

template <class T>
std::string str(const std::vector<T>& v);
template <class K, class V>
std::string str(const std::map<K, V>& m);

// ===================== insertion-ordered dict =====================
// Python dicts preserve insertion order; std::map sorts by key. This drop-in
// container behaves like a mapping while iterating/printing in the order the
// keys were first inserted.
template <class K, class V>
struct dict {
    std::vector<std::pair<K, V>> items;
    using value_type = std::pair<K, V>;
    using key_type = K;
    using mapped_type = V;
    using iterator = typename std::vector<std::pair<K, V>>::iterator;
    using const_iterator = typename std::vector<std::pair<K, V>>::const_iterator;

    dict() = default;
    dict(std::initializer_list<std::pair<K, V>> il) {
        for (const auto& p : il) (*this)[p.first] = p.second;
    }

    iterator begin() { return items.begin(); }
    iterator end() { return items.end(); }
    const_iterator begin() const { return items.begin(); }
    const_iterator end() const { return items.end(); }

    std::size_t size() const { return items.size(); }
    bool empty() const { return items.empty(); }

    iterator find(const K& k) {
        for (auto it = items.begin(); it != items.end(); ++it)
            if (it->first == k) return it;
        return items.end();
    }
    const_iterator find(const K& k) const {
        for (auto it = items.begin(); it != items.end(); ++it)
            if (it->first == k) return it;
        return items.end();
    }
    std::size_t count(const K& k) const { return find(k) == items.end() ? 0 : 1; }

    V& operator[](const K& k) {
        for (auto& p : items)
            if (p.first == k) return p.second;
        items.push_back(std::make_pair(k, V{}));
        return items.back().second;
    }

    std::vector<K> keys() const {
        std::vector<K> r;
        r.reserve(items.size());
        for (const auto& p : items) r.push_back(p.first);
        return r;
    }
    std::vector<V> values() const {
        std::vector<V> r;
        r.reserve(items.size());
        for (const auto& p : items) r.push_back(p.second);
        return r;
    }
};

template <class K, class V>
std::string str(const dict<K, V>& m);
template <class T>
std::string str(const std::set<T>& s);

inline std::string repr(const std::string& s) {
    std::string r = "'";
    for (char c : s) {
        if (c == '\\') r += "\\\\";
        else if (c == '\'') r += "\\'";
        else if (c == '\n') r += "\\n";
        else if (c == '\t') r += "\\t";
        else r += c;
    }
    return r + "'";
}
inline std::string repr(char c) { return repr(std::string(1, c)); }
// Defined at the end of the runtime: `str` is called unqualified from here, so
// every str() overload must already be visible (no ADL reaches namespace py).
template <class T>
std::string repr(const T& v);

template <class A, class B>
std::string str(const std::pair<A, B>& p) {
    return "(" + repr(p.first) + ", " + repr(p.second) + ")";
}

template <class Tuple, std::size_t... I>
std::string tuple_str(const Tuple& t, std::index_sequence<I...>) {
    std::string r = "(";
    bool first = true;
    ((r += (first ? "" : ", ") + repr(std::get<I>(t)), first = false), ...);
    return r + ")";
}
template <class... Ts>
std::string str(const std::tuple<Ts...>& t) {
    if constexpr (sizeof...(Ts) == 1)
        return "(" + repr(std::get<0>(t)) + ",)";
    else
        return tuple_str(t, std::index_sequence_for<Ts...>{});
}

template <class T>
std::string str(const std::vector<T>& v) {
    std::string r = "[";
    for (std::size_t i = 0; i < v.size(); ++i) {
        if (i) r += ", ";
        r += repr(v[i]);
    }
    return r + "]";
}
template <class K, class V>
std::string str(const std::map<K, V>& m) {
    std::string r = "{";
    bool first = true;
    for (const auto& kv : m) {
        if (!first) r += ", ";
        first = false;
        r += repr(kv.first) + ": " + repr(kv.second);
    }
    return r + "}";
}
template <class K, class V>
std::string str(const dict<K, V>& m) {
    std::string r = "{";
    bool first = true;
    for (const auto& kv : m) {
        if (!first) r += ", ";
        first = false;
        r += repr(kv.first) + ": " + repr(kv.second);
    }
    return r + "}";
}
template <class T>
std::string str(const std::set<T>& s) {
    if (s.empty()) return "set()";
    std::string r = "{";
    bool first = true;
    for (const auto& e : s) {
        if (!first) r += ", ";
        first = false;
        r += repr(e);
    }
    return r + "}";
}
template <class T,
          class = std::enable_if_t<!std::is_arithmetic_v<T> && !std::is_same_v<T, std::string>>>
std::string str(const T& v) {
    std::ostringstream os;
    os << v;
    return os.str();
}

// ===================== free functions =====================
inline std::string str_of(const char* v) { return std::string(v); }
inline std::string py_str(const std::string& v) { return v; }
inline std::string py_str(const char* v) { return std::string(v); }
inline std::string py_str(bool v) { return str(v); }

// ---- uniform "iterable" view ----------------------------------------------
// In Python a str is a sequence of exactly its characters.  In C++ a string
// *literal* is a `const char[N]` array whose trailing '\0' would be iterated as
// an extra element (so `enumerate("abc")` yielded 4 entries).  `seq()` maps any
// char array / char pointer to a std::string and leaves every other container
// untouched (returned by const reference).
template <class C>
decltype(auto) seq(const C& c) {
    using D = std::remove_cv_t<std::remove_reference_t<C>>;
    if constexpr (std::is_pointer_v<D> &&
                  std::is_same_v<std::remove_cv_t<std::remove_pointer_t<D>>, char>) {
        return std::string(c);
    } else if constexpr (std::is_array_v<D> &&
                         std::is_same_v<std::remove_cv_t<std::remove_extent_t<D>>, char>) {
        return std::string(c);
    } else {
        return (c);
    }
}
template <class C>
using seq_t = std::remove_cv_t<std::remove_reference_t<decltype(seq(std::declval<const C&>()))>>;
// Element type of any iterable, including arrays and string literals.
template <class C>
using elem_t =
    std::remove_cv_t<std::remove_reference_t<decltype(*std::begin(std::declval<const seq_t<C>&>()))>>;

template <class T>
inline long long len(const T& c) {
    return static_cast<long long>(seq(c).size());
}

// membership tests
inline bool contains(const std::string& s, const std::string& sub) {
    return s.find(sub) != std::string::npos;
}
inline bool contains(const std::string& s, const char* sub) { return s.find(sub) != std::string::npos; }
inline bool contains(const std::string& s, char c) { return s.find(c) != std::string::npos; }
template <class T, class V>
inline bool contains(const std::vector<T>& c, const V& v) {
    return std::find(c.begin(), c.end(), v) != c.end();
}
template <class K, class V, class Q>
inline bool contains(const std::map<K, V>& m, const Q& q) {
    return m.find(q) != m.end();
}
template <class K, class V, class Q>
inline bool contains(const dict<K, V>& m, const Q& q) {
    return m.find(q) != m.end();
}
template <class T, class Q>
inline bool contains(const std::set<T>& s, const Q& q) {
    return s.find(q) != s.end();
}
template <class A, class B>
inline bool contains(const std::pair<A, B>& p, const A& k) {
    return p.first == k;
}

// ===================== indexing =====================
template <class C>
decltype(auto) item(C&& c, long long i) {
    long long n = static_cast<long long>(c.size());
    if (i < 0) i += n;
    if (i < 0 || i >= n) throw IndexError("index out of range");
    using V = std::remove_cv_t<std::remove_reference_t<decltype(c[static_cast<std::size_t>(0)])>>;
    if constexpr (std::is_same_v<V, char>)
        return std::string(1, c[static_cast<std::size_t>(i)]);
    else
        return c[static_cast<std::size_t>(i)];
}

template <class M, class K>
decltype(auto) dget(M&& m, const K& k) {
    auto it = m.find(k);
    if (it == m.end()) throw KeyError("key not found");
    return (it->second);  // parenthesised: return the stored lvalue, not a copy
}

// Python iterates a str as a sequence of 1-character strings.
inline std::vector<std::string> py_chars(const std::string& s) {
    std::vector<std::string> r;
    r.reserve(s.size());
    for (char c : s) r.emplace_back(1, c);
    return r;
}

// slicing (NONE_LL means "omitted")
template <class T>
std::vector<T> slice(const std::vector<T>& v, long long lo, long long hi) {
    long long n = static_cast<long long>(v.size());
    if (lo == NONE_LL) lo = 0;
    if (hi == NONE_LL) hi = n;
    if (lo < 0) lo += n;
    if (hi < 0) hi += n;
    lo = std::max<long long>(0, std::min(lo, n));
    hi = std::max<long long>(0, std::min(hi, n));
    if (hi < lo) hi = lo;
    return std::vector<T>(v.begin() + lo, v.begin() + hi);
}
inline std::string slice(const std::string& s, long long lo, long long hi) {
    long long n = static_cast<long long>(s.size());
    if (lo == NONE_LL) lo = 0;
    if (hi == NONE_LL) hi = n;
    if (lo < 0) lo += n;
    if (hi < 0) hi += n;
    lo = std::max<long long>(0, std::min(lo, n));
    hi = std::max<long long>(0, std::min(hi, n));
    if (hi < lo) hi = lo;
    return s.substr(static_cast<std::size_t>(lo), static_cast<std::size_t>(hi - lo));
}
template <class T>
std::vector<T> slice_step(const std::vector<T>& v, long long lo, long long hi, long long step) {
    long long n = static_cast<long long>(v.size());
    if (step == 0) throw ValueError("slice step cannot be zero");
    if (step > 0) {
        if (lo == NONE_LL) lo = 0;
        if (hi == NONE_LL) hi = n;
        if (lo < 0) lo += n;
        if (hi < 0) hi += n;
        lo = std::max<long long>(0, std::min(lo, n));
        hi = std::max<long long>(0, std::min(hi, n));
        std::vector<T> r;
        for (long long i = lo; i < hi; i += step) r.push_back(v[static_cast<std::size_t>(i)]);
        return r;
    }
    if (lo == NONE_LL) lo = n - 1;
    if (hi == NONE_LL) hi = -n - 1;
    if (lo < 0) lo += n;
    if (hi < 0) hi += n;
    lo = std::max<long long>(-1, std::min(lo, n - 1));
    hi = std::max<long long>(-1, std::min(hi, n - 1));
    std::vector<T> r;
    for (long long i = lo; i > hi; i += step) r.push_back(v[static_cast<std::size_t>(i)]);
    return r;
}
inline std::string slice_step(const std::string& s, long long lo, long long hi, long long step) {
    std::vector<char> v(s.begin(), s.end());
    auto r = slice_step(v, lo, hi, step);
    return std::string(r.begin(), r.end());
}

// ===================== numeric semantics =====================
template <class A, class B,
          class = std::enable_if_t<std::is_arithmetic_v<A> && std::is_arithmetic_v<B>>>
inline double truediv(A a, B b) {
    double db = static_cast<double>(b);
    if (db == 0.0) throw ZeroDivisionError("division by zero");
    return static_cast<double>(a) / db;
}

template <class A, class B,
          class = std::enable_if_t<std::is_arithmetic_v<A> && std::is_arithmetic_v<B>>>
inline auto floordiv(A a, B b) {
    double db = static_cast<double>(b);
    if (db == 0.0) throw ZeroDivisionError("integer division or modulo by zero");
    double r = std::floor(static_cast<double>(a) / db);
    if constexpr (std::is_integral_v<A> && std::is_integral_v<B>)
        return static_cast<long long>(r);
    else
        return r;
}

template <class A, class B,
          class = std::enable_if_t<std::is_arithmetic_v<A> && std::is_arithmetic_v<B>>>
inline auto pymod(A a, B b) {
    double db = static_cast<double>(b);
    if (db == 0.0) throw ZeroDivisionError("integer division or modulo by zero");
    if constexpr (std::is_integral_v<A> && std::is_integral_v<B>) {
        long long la = static_cast<long long>(a), lb = static_cast<long long>(b);
        long long r = la % lb;
        if (r != 0 && ((r < 0) != (lb < 0))) r += lb;
        return r;
    } else {
        double r = std::fmod(static_cast<double>(a), db);
        if (r != 0 && ((r < 0) != (db < 0))) r += db;
        return r;
    }
}

template <class A, class B,
          class = std::enable_if_t<std::is_arithmetic_v<A> && std::is_arithmetic_v<B>>>
inline auto power(A a, B b) {
    if constexpr (std::is_integral_v<A> && std::is_integral_v<B>) {
        long long e = static_cast<long long>(b);
        if (e >= 0) {
            long long result = 1, base = static_cast<long long>(a);
            while (e) {
                if (e & 1) result *= base;
                base *= base;
                e >>= 1;
            }
            return result;
        }
        return static_cast<long long>(static_cast<double>(0));
    } else {
        return std::pow(static_cast<double>(a), static_cast<double>(b));
    }
}

inline long long int_div_floor(long long a, long long b) {
    if (b == 0) throw ZeroDivisionError("integer division or modulo by zero");
    long long q = a / b;
    if ((a % b != 0) && ((a < 0) != (b < 0))) --q;
    return q;
}

// ===================== conversions =====================
inline long long to_int(long long v) { return v; }
inline long long to_int(int v) { return v; }
inline long long to_int(bool v) { return v ? 1 : 0; }
inline long long to_int(char v) { return v; }
inline long long to_int(double v) { return static_cast<long long>(std::trunc(v)); }
inline long long to_int(const std::string& s) {
    std::string t;
    for (char c : s)
        if (!std::isspace(static_cast<unsigned char>(c))) t += c;
    if (t.empty()) throw ValueError("invalid literal for int()");
    std::size_t used = 0;
    long long v = 0;
    try {
        v = std::stoll(t, &used, 10);
    } catch (...) {
        throw ValueError("invalid literal for int(): " + s);
    }
    if (used != t.size()) throw ValueError("invalid literal for int(): " + s);
    return v;
}
inline long long to_int(const char* s) { return to_int(std::string(s)); }

inline double to_float(double v) { return v; }
inline double to_float(long long v) { return static_cast<double>(v); }
inline double to_float(const std::string& s) {
    std::string t;
    for (char c : s)
        if (!std::isspace(static_cast<unsigned char>(c))) t += c;
    if (t.empty()) throw ValueError("could not convert string to float: " + s);
    std::size_t used = 0;
    double v = 0;
    try {
        v = std::stod(t, &used);
    } catch (...) {
        throw ValueError("could not convert string to float: " + s);
    }
    if (used != t.size()) throw ValueError("could not convert string to float: " + s);
    return v;
}
inline double to_float(const char* s) { return to_float(std::string(s)); }

inline bool to_bool(bool v) { return v; }
inline bool to_bool(long long v) { return v != 0; }
inline bool to_bool(int v) { return v != 0; }
inline bool to_bool(double v) { return v != 0.0; }
inline bool to_bool(const std::string& s) { return !s.empty(); }
inline bool to_bool(const char* s) { return s && *s; }
template <class T>
inline bool to_bool(const std::vector<T>& v) { return !v.empty(); }
template <class K, class V>
inline bool to_bool(const std::map<K, V>& m) { return !m.empty(); }
template <class K, class V>
inline bool to_bool(const dict<K, V>& m) { return !m.empty(); }

// ===================== math / builtins =====================
inline long long py_abs(long long v) { return v < 0 ? -v : v; }
inline long long py_abs(int v) { return v < 0 ? -static_cast<long long>(v) : v; }
inline double py_abs(double v) { return std::fabs(v); }

inline long long py_round(double v) {
    double r = std::nearbyint(v);  // banker's rounding, like Python
    return static_cast<long long>(r);
}
inline double py_round(double v, long long digits) {
    double f = std::pow(10.0, static_cast<double>(digits));
    return std::nearbyint(v * f) / f;
}

template <class C>
auto py_min(const C& c) {
    const auto& cc = seq(c);
    if (cc.begin() == cc.end()) throw ValueError("min() arg is an empty sequence");
    return *std::min_element(cc.begin(), cc.end());
}
template <class C>
auto py_max(const C& c) {
    const auto& cc = seq(c);
    if (cc.begin() == cc.end()) throw ValueError("max() arg is an empty sequence");
    return *std::max_element(cc.begin(), cc.end());
}

// min(a, b, ...) / max(a, b, ...) with possibly different numeric types:
// std::min/std::max would fail to deduce a common type.
template <class First, class... Rest>
auto py_min_of(First first, Rest... rest) {
    using C = std::common_type_t<First, Rest..., First>;
    C acc = static_cast<C>(first);
    for (const C& v : std::initializer_list<C>{static_cast<C>(rest)...})
        if (v < acc) acc = v;
    return acc;
}
template <class First, class... Rest>
auto py_max_of(First first, Rest... rest) {
    using C = std::common_type_t<First, Rest..., First>;
    C acc = static_cast<C>(first);
    for (const C& v : std::initializer_list<C>{static_cast<C>(rest)...})
        if (acc < v) acc = v;
    return acc;
}

template <class C>
auto py_sum(const C& c) {
    const auto& cc = seq(c);
    elem_t<C> acc{};
    for (const auto& e : cc) acc += e;
    return acc;
}
template <class C, class T>
auto py_sum(const C& c, T start) {
    T acc = start;
    for (const auto& e : seq(c)) acc += e;
    return acc;
}

template <class C>
auto py_sorted(const C& c) {
    const auto& cc = seq(c);
    std::vector<elem_t<C>> v(std::begin(cc), std::end(cc));
    std::sort(v.begin(), v.end());
    return v;
}
template <class C, class Key>
auto py_sorted(const C& c, Key key, bool reverse = false) {
    const auto& cc = seq(c);
    std::vector<elem_t<C>> v(std::begin(cc), std::end(cc));
    if (reverse)
        std::sort(v.begin(), v.end(), [&](const auto& a, const auto& b) { return key(a) > key(b); });
    else
        std::sort(v.begin(), v.end(), [&](const auto& a, const auto& b) { return key(a) < key(b); });
    return v;
}
template <class C>
auto py_sorted_rev(const C& c) {
    const auto& cc = seq(c);
    std::vector<elem_t<C>> v(std::begin(cc), std::end(cc));
    std::sort(v.begin(), v.end(), std::greater<>());
    return v;
}

template <class C, class Key>
auto py_sort_by(C& c, Key key, bool reverse = false) {
    if (reverse)
        std::stable_sort(c.begin(), c.end(), [&](const auto& a, const auto& b) { return key(a) > key(b); });
    else
        std::stable_sort(c.begin(), c.end(), [&](const auto& a, const auto& b) { return key(a) < key(b); });
}

template <class C>
auto enumerate(const C& c) {
    const auto& cc = seq(c);
    std::vector<std::pair<long long, elem_t<C>>> r;
    long long i = 0;
    for (const auto& e : cc) r.emplace_back(i++, e);
    return r;
}
template <class C>
auto enumerate_from(const C& c, long long start) {
    const auto& cc = seq(c);
    std::vector<std::pair<long long, elem_t<C>>> r;
    long long i = start;
    for (const auto& e : cc) r.emplace_back(i++, e);
    return r;
}

template <class K, class V>
std::vector<V> map_values(const std::map<K, V>& m) {
    std::vector<V> r;
    for (const auto& kv : m) r.push_back(kv.second);
    return r;
}
template <class K, class V>
std::vector<V> map_values(const dict<K, V>& m) {
    std::vector<V> r;
    r.reserve(m.items.size());
    for (const auto& kv : m) r.push_back(kv.second);
    return r;
}
// subscript store:  m[k] = v  (works for std::map and py::dict)
template <class M, class K, class V>
void dset(M& m, const K& k, const V& v) {
    m[k] = v;
}
template <class M, class K>
auto dget_or(const M& m, const K& k) {
    auto it = m.find(k);
    if (it == m.end()) throw KeyError("key not found");
    return it->second;
}
template <class M, class K, class D>
auto dget_or(const M& m, const K& k, const D& def) {
    auto it = m.find(k);
    return it == m.end() ? static_cast<typename M::mapped_type>(def) : it->second;
}

template <class C>
bool any_of(const C& c) {
    for (const auto& e : seq(c))
        if (to_bool(e)) return true;
    return false;
}
template <class C>
bool all_of(const C& c) {
    for (const auto& e : seq(c))
        if (!to_bool(e)) return false;
    return true;
}

// map(f, xs) / filter(f, xs) -- return lists so they can be printed/iterated.
template <class F, class C>
auto py_map(F f, const C& c) {
    const auto& cc = seq(c);
    using R = std::remove_cv_t<std::remove_reference_t<decltype(f(*std::begin(cc)))>>;
    std::vector<R> r;
    r.reserve(cc.size());
    for (const auto& e : cc) r.push_back(f(e));
    return r;
}
template <class F, class C>
auto py_filter(F f, const C& c) {
    const auto& cc = seq(c);
    using R = elem_t<C>;
    std::vector<R> r;
    for (const auto& e : cc)
        if (to_bool(f(e))) r.push_back(e);
    return r;
}
template <class C>
auto py_reversed(const C& c) {
    const auto& cc = seq(c);
    std::vector<elem_t<C>> r(cc.rbegin(), cc.rend());
    return r;
}
inline std::string py_reversed(const std::string& s) {
    return std::string(s.rbegin(), s.rend());
}

inline std::mt19937_64& rng();

inline double uniform(double a, double b) {
    return std::uniform_real_distribution<double>(a, b)(rng());
}
inline double time_now() {
    using namespace std::chrono;
    return duration<double>(system_clock::now().time_since_epoch()).count();
}

template <class A, class B>
auto zip2(const A& a, const B& b) {
    const auto& aa = seq(a);
    const auto& bb = seq(b);
    std::vector<elem_t<A>> va(std::begin(aa), std::end(aa));
    std::vector<elem_t<B>> vb(std::begin(bb), std::end(bb));
    std::vector<std::pair<elem_t<A>, elem_t<B>>> r;
    std::size_t n = std::min(va.size(), vb.size());
    for (std::size_t i = 0; i < n; ++i) r.emplace_back(va[i], vb[i]);
    return r;
}

inline std::vector<long long> xrange(long long start, long long stop, long long step) {
    if (step == 0) throw ValueError("range() arg 3 must not be zero");
    std::vector<long long> r;
    if (step > 0)
        for (long long i = start; i < stop; i += step) r.push_back(i);
    else
        for (long long i = start; i > stop; i += step) r.push_back(i);
    return r;
}
inline std::vector<long long> xrange(long long stop) { return xrange(0, stop, 1); }
inline std::vector<long long> xrange(long long start, long long stop) { return xrange(start, stop, 1); }

template <class T>
std::vector<T> to_list(const std::vector<T>& v) { return v; }
inline std::vector<std::string> to_list(const std::string& s) {
    std::vector<std::string> r;
    for (char c : s) r.push_back(std::string(1, c));
    return r;
}
template <class K, class V>
std::vector<K> to_list_keys(const std::map<K, V>& m) {
    std::vector<K> r;
    for (const auto& kv : m) r.push_back(kv.first);
    return r;
}
template <class K, class V>
std::vector<K> to_list_keys(const dict<K, V>& m) { return m.keys(); }
template <class T>
std::vector<T> to_list_set(const std::set<T>& s) { return std::vector<T>(s.begin(), s.end()); }

// ---- set algebra (Python's | & - on sets) ---------------------------------
template <class A, class B>
auto set_union(const A& a, const B& b) {
    std::set<elem_t<A>> r(a.begin(), a.end());
    for (const auto& e : b) r.insert(e);
    return r;
}
template <class A, class B>
auto set_inter(const A& a, const B& b) {
    std::set<elem_t<A>> r;
    for (const auto& e : a)
        if (b.count(e)) r.insert(e);
    return r;
}
template <class A, class B>
auto set_diff(const A& a, const B& b) {
    std::set<elem_t<A>> r;
    for (const auto& e : a)
        if (!b.count(e)) r.insert(e);
    return r;
}
template <class A, class B>
bool set_subset(const A& a, const B& b) {
    for (const auto& e : a)
        if (!b.count(e)) return false;
    return true;
}
template <class A>
void set_remove(A& a, const elem_t<A>& x) {
    auto it = a.find(x);
    if (it == a.end()) throw KeyError("element not found");
    a.erase(it);
}

inline std::vector<std::string> split(const std::string& s, const std::string& sep = "") {
    std::vector<std::string> r;
    if (sep.empty()) {
        std::size_t i = 0;
        while (i < s.size()) {
            while (i < s.size() && std::isspace(static_cast<unsigned char>(s[i]))) i++;
            std::size_t j = i;
            while (j < s.size() && !std::isspace(static_cast<unsigned char>(s[j]))) j++;
            if (j > i) r.push_back(s.substr(i, j - i));
            i = j;
        }
        return r;
    }
    std::size_t pos = 0;
    while (true) {
        std::size_t k = s.find(sep, pos);
        if (k == std::string::npos) {
            r.push_back(s.substr(pos));
            break;
        }
        r.push_back(s.substr(pos, k - pos));
        pos = k + sep.size();
    }
    return r;
}
inline std::vector<std::string> split(const std::string& s, const std::string& sep, long long maxsplit) {
    std::vector<std::string> r;
    if (maxsplit < 0) return split(s, sep);
    if (sep.empty()) {
        std::size_t i = 0;
        long long done = 0;
        while (i < s.size()) {
            while (i < s.size() && std::isspace(static_cast<unsigned char>(s[i]))) i++;
            if (i >= s.size()) break;
            if (done == maxsplit) {
                r.push_back(s.substr(i));
                break;
            }
            std::size_t j = i;
            while (j < s.size() && !std::isspace(static_cast<unsigned char>(s[j]))) j++;
            r.push_back(s.substr(i, j - i));
            i = j;
            done++;
        }
        return r;
    }
    std::size_t pos = 0;
    long long done = 0;
    while (done < maxsplit) {
        std::size_t k = s.find(sep, pos);
        if (k == std::string::npos) break;
        r.push_back(s.substr(pos, k - pos));
        pos = k + sep.size();
        done++;
    }
    r.push_back(s.substr(pos));
    return r;
}

template <class C>
std::string join(const std::string& sep, const C& parts) {
    std::string r;
    bool first = true;
    for (const auto& p : parts) {
        if (!first) r += sep;
        first = false;
        r += str(p);
    }
    return r;
}

inline std::string upper(std::string s) {
    for (auto& c : s) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    return s;
}
inline std::string lower(std::string s) {
    for (auto& c : s) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return s;
}
inline std::string strip(const std::string& s, const std::string& chars = " \t\n\r\f\v") {
    std::size_t a = s.find_first_not_of(chars);
    if (a == std::string::npos) return "";
    std::size_t b = s.find_last_not_of(chars);
    return s.substr(a, b - a + 1);
}
inline std::string lstrip(const std::string& s, const std::string& chars = " \t\n\r\f\v") {
    std::size_t a = s.find_first_not_of(chars);
    return a == std::string::npos ? "" : s.substr(a);
}
inline std::string rstrip(const std::string& s, const std::string& chars = " \t\n\r\f\v") {
    std::size_t b = s.find_last_not_of(chars);
    return b == std::string::npos ? "" : s.substr(0, b + 1);
}
inline std::string replace(const std::string& s, const std::string& from, const std::string& to) {
    if (from.empty()) return s;
    std::string r;
    std::size_t pos = 0;
    while (true) {
        std::size_t k = s.find(from, pos);
        if (k == std::string::npos) {
            r += s.substr(pos);
            break;
        }
        r += s.substr(pos, k - pos);
        r += to;
        pos = k + from.size();
    }
    return r;
}
inline bool startswith(const std::string& s, const std::string& p) {
    return s.size() >= p.size() && s.compare(0, p.size(), p) == 0;
}
inline bool endswith(const std::string& s, const std::string& p) {
    return s.size() >= p.size() && s.compare(s.size() - p.size(), p.size(), p) == 0;
}
inline long long find(const std::string& s, const std::string& sub) {
    std::size_t k = s.find(sub);
    return k == std::string::npos ? -1 : static_cast<long long>(k);
}
inline long long rfind(const std::string& s, const std::string& sub) {
    std::size_t k = s.rfind(sub);
    return k == std::string::npos ? -1 : static_cast<long long>(k);
}
inline long long count_sub(const std::string& s, const std::string& sub) {
    if (sub.empty()) return static_cast<long long>(s.size()) + 1;
    long long n = 0;
    std::size_t pos = 0;
    while ((pos = s.find(sub, pos)) != std::string::npos) {
        n++;
        pos += sub.size();
    }
    return n;
}
inline std::string capitalize(std::string s) {
    if (s.empty()) return s;
    std::string r = lower(s);
    r[0] = static_cast<char>(std::toupper(static_cast<unsigned char>(r[0])));
    return r;
}
inline std::string title(std::string s) {
    bool start = true;
    for (auto& c : s) {
        if (std::isalpha(static_cast<unsigned char>(c))) {
            c = start ? static_cast<char>(std::toupper(static_cast<unsigned char>(c)))
                      : static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
            start = false;
        } else {
            start = true;
        }
    }
    return s;
}
inline std::string zfill(const std::string& s, long long width) {
    bool neg = !s.empty() && (s[0] == '-' || s[0] == '+');
    std::string body = neg ? s.substr(1) : s;
    while (static_cast<long long>(body.size()) < width - (neg ? 1 : 0)) body = "0" + body;
    return (neg ? std::string(1, s[0]) : "") + body;
}
inline std::string repeat(const std::string& s, long long n) {
    std::string r;
    for (long long i = 0; i < n; ++i) r += s;
    return r;
}
// list * int  /  int * list  (Python sequence repetition)
template <class T>
std::vector<T> repeat(const std::vector<T>& v, long long n) {
    std::vector<T> r;
    if (n <= 0) return r;
    r.reserve(v.size() * static_cast<std::size_t>(n));
    for (long long i = 0; i < n; ++i) r.insert(r.end(), v.begin(), v.end());
    return r;
}
inline std::string chr_of(long long c) { return std::string(1, static_cast<char>(c)); }
inline long long ord_of(const std::string& s) {
    if (s.empty()) throw ValueError("ord() expected a character");
    return static_cast<long long>(static_cast<unsigned char>(s[0]));
}
inline bool isdigit_(const std::string& s) {
    if (s.empty()) return false;
    for (char c : s)
        if (!std::isdigit(static_cast<unsigned char>(c))) return false;
    return true;
}
inline bool isalpha_(const std::string& s) {
    if (s.empty()) return false;
    for (char c : s)
        if (!std::isalpha(static_cast<unsigned char>(c))) return false;
    return true;
}
inline bool isspace_(const std::string& s) {
    if (s.empty()) return false;
    for (char c : s)
        if (!std::isspace(static_cast<unsigned char>(c))) return false;
    return true;
}
inline bool isalnum_(const std::string& s) {
    if (s.empty()) return false;
    for (char c : s)
        if (!std::isalnum(static_cast<unsigned char>(c))) return false;
    return true;
}

// list helpers
template <class T, class V>
void append(std::vector<T>& v, const V& x) {
    v.push_back(x);
}
template <class T, class C>
void extend(std::vector<T>& v, const C& xs) {
    v.insert(v.end(), xs.begin(), xs.end());
}
template <class T>
T pop(std::vector<T>& v) {
    if (v.empty()) throw IndexError("pop from empty list");
    T x = v.back();
    v.pop_back();
    return x;
}
template <class T>
T pop(std::vector<T>& v, long long i) {
    long long n = static_cast<long long>(v.size());
    if (i < 0) i += n;
    if (i < 0 || i >= n) throw IndexError("pop index out of range");
    T x = v[static_cast<std::size_t>(i)];
    v.erase(v.begin() + i);
    return x;
}
template <class T, class V>
void remove(std::vector<T>& v, const V& x) {
    auto it = std::find(v.begin(), v.end(), x);
    if (it == v.end()) throw ValueError("list.remove(x): x not in list");
    v.erase(it);
}
template <class T, class V>
long long index_of(const std::vector<T>& v, const V& x) {
    auto it = std::find(v.begin(), v.end(), x);
    if (it == v.end()) throw ValueError("value is not in list");
    return static_cast<long long>(it - v.begin());
}
template <class T, class V>
long long count_in(const std::vector<T>& v, const V& x) {
    long long n = 0;
    for (const auto& e : v)
        if (e == x) n++;
    return n;
}
template <class T>
void sort_inplace(std::vector<T>& v, bool reverse = false) {
    if (reverse)
        std::sort(v.begin(), v.end(), std::greater<>());
    else
        std::sort(v.begin(), v.end());
}
template <class T>
void reverse_inplace(std::vector<T>& v) {
    std::reverse(v.begin(), v.end());
}

template <class T>
std::vector<T> reversed(const std::vector<T>& v) {
    std::vector<T> r(v.rbegin(), v.rend());
    return r;
}
inline std::string reversed(const std::string& s) {
    return std::string(s.rbegin(), s.rend());
}

template <class T>
std::vector<T> concat(const std::vector<T>& a, const std::vector<T>& b) {
    std::vector<T> r = a;
    r.insert(r.end(), b.begin(), b.end());
    return r;
}

// Materialise a `*args` parameter pack into a vector.  An empty pack has no
// common type, so `long long` is always appended to anchor the result.
template <class... Ts>
auto make_list(Ts... vs) {
    using First = std::tuple_element_t<0, std::tuple<Ts..., long long>>;
    if constexpr (sizeof...(Ts) > 0 && !std::is_arithmetic_v<First>) {
        using E = std::common_type_t<Ts...>;
        return std::vector<E>{vs...};
    } else {
        using E = std::common_type_t<Ts..., long long>;
        return std::vector<E>{static_cast<E>(vs)...};
    }
}
// ===================== i/o =====================
inline std::vector<std::string> argv_store;

inline void init_argv(int argc, char** argv) {
    argv_store.clear();
    for (int i = 0; i < argc; ++i) argv_store.push_back(argv[i]);
}

inline std::string input(const std::string& prompt = "") {
    if (!prompt.empty()) {
        std::cout << prompt << std::flush;
    }
    std::string s;
    if (!std::getline(std::cin, s)) throw Exception("EOFError: EOF when reading a line");
    return s;
}

inline void assert_(bool cond, const std::string& msg = "AssertionError") {
    if (!cond) throw Exception("AssertionError: " + msg);
}

inline void exit_(long long code) { std::exit(static_cast<int>(code)); }


// ===================== format() for f-strings =====================
// Python format specification (mini-language):
//   [[fill]align][sign][#][0][width][grouping][.precision][type]
struct FmtSpec {
    char fill = ' ';
    char align = 0;      // '<' '>' '^'
    char sign = 0;       // '+' '-' ' '
    bool alt = false;    // '#'
    bool zero = false;   // leading '0'
    bool hasType = false;
    long long width = 0;
    char sep = 0;        // ',' or '_'
    int prec = -1;
    char type = 0;
};

inline FmtSpec parseFmtSpec(const std::string& spec) {
    FmtSpec sp;
    std::size_t i = 0, n = spec.size();
    if (n >= 2 && (spec[1] == '<' || spec[1] == '>' || spec[1] == '^')) {
        sp.fill = spec[0];
        sp.align = spec[1];
        i = 2;
    } else if (n >= 1 && (spec[0] == '<' || spec[0] == '>' || spec[0] == '^')) {
        sp.align = spec[0];
        i = 1;
    }
    if (i < n && (spec[i] == '+' || spec[i] == '-' || spec[i] == ' ')) sp.sign = spec[i++];
    if (i < n && spec[i] == '#') { sp.alt = true; ++i; }
    if (i < n && spec[i] == '0') { sp.zero = true; ++i; }
    while (i < n && std::isdigit(static_cast<unsigned char>(spec[i])))
        sp.width = sp.width * 10 + (spec[i++] - '0');
    if (i < n && (spec[i] == ',' || spec[i] == '_')) sp.sep = spec[i++];
    if (i < n && spec[i] == '.') {
        ++i;
        sp.prec = 0;
        while (i < n && std::isdigit(static_cast<unsigned char>(spec[i])))
            sp.prec = sp.prec * 10 + (spec[i++] - '0');
    }
    if (i < n) { sp.type = spec[i++]; sp.hasType = true; }
    return sp;
}

inline std::string fmtGroup(const std::string& digits, char sep) {
    std::string out;
    for (std::size_t k = 0; k < digits.size(); ++k) {
        if (k > 0 && (digits.size() - k) % 3 == 0) out += sep;
        out += digits[k];
    }
    return out;
}

inline std::string fmtPad(const std::string& body, const FmtSpec& sp, bool numeric) {
    if (sp.width <= static_cast<long long>(body.size())) return body;
    long long pad = sp.width - static_cast<long long>(body.size());
    char align = sp.align ? sp.align : (numeric ? '>' : '<');
    if (sp.zero && sp.align == 0) {
        std::string signPart, rest = body;
        if (!rest.empty() && (rest[0] == '-' || rest[0] == '+' || rest[0] == ' ')) {
            signPart = rest.substr(0, 1);
            rest.erase(0, 1);
        }
        std::string prefix;
        if (rest.size() >= 2 && rest[0] == '0' &&
            (rest[1] == 'x' || rest[1] == 'X' || rest[1] == 'o' || rest[1] == 'b' ||
             rest[1] == 'B')) {
            prefix = rest.substr(0, 2);
            rest.erase(0, 2);
        }
        return signPart + prefix + std::string(static_cast<std::size_t>(pad), '0') + rest;
    }
    std::string f(static_cast<std::size_t>(pad), sp.fill);
    if (align == '<') return body + f;
    if (align == '^') {
        long long l = pad / 2;
        return std::string(static_cast<std::size_t>(l), sp.fill) + body +
               std::string(static_cast<std::size_t>(pad - l), sp.fill);
    }
    return f + body;
}

inline std::string fmtApplySign(const std::string& mag, bool neg, const FmtSpec& sp) {
    if (neg) return "-" + mag;
    if (sp.sign == '+') return "+" + mag;
    if (sp.sign == ' ') return " " + mag;
    return mag;
}

inline std::string fmtDouble(double v, const FmtSpec& sp) {
    if (std::isnan(v)) return "nan";
    bool neg = std::signbit(v);
    if (std::isinf(v)) return fmtPad(fmtApplySign("inf", neg, sp), sp, true);
    char type = sp.hasType ? sp.type : 0;
    char buf[512];
    std::string mag;
    if (type == 'f' || type == 'F') {
        int prec = sp.prec < 0 ? 6 : sp.prec;
        std::snprintf(buf, sizeof(buf), "%.*f", prec, std::fabs(v));
        mag = buf;
    } else if (type == 'e' || type == 'E') {
        int prec = sp.prec < 0 ? 6 : sp.prec;
        std::snprintf(buf, sizeof(buf), "%.*e", prec, std::fabs(v));
        mag = buf;
        if (type == 'E')
            for (auto& c : mag) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    } else if (type == 'g' || type == 'G') {
        int prec = sp.prec < 0 ? 6 : sp.prec;
        std::snprintf(buf, sizeof(buf), "%.*g", prec, std::fabs(v));
        mag = buf;
        if (type == 'G')
            for (auto& c : mag) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    } else if (type == '%') {
        int prec = sp.prec < 0 ? 6 : sp.prec;
        std::snprintf(buf, sizeof(buf), "%.*f", prec, std::fabs(v) * 100.0);
        mag = std::string(buf) + "%";
    } else if (type == 'd') {
        mag = std::to_string(static_cast<long long>(std::fabs(v)));
    } else {
        std::string s = str(v);
        if (!s.empty() && (s[0] == '-' || s[0] == '+')) s.erase(0, 1);
        return fmtPad(fmtApplySign(s, neg, sp), sp, true);
    }
    return fmtPad(fmtApplySign(mag, neg, sp), sp, true);
}

// Integral formatting (d/x/X/o/b/c) plus float conversions on integral values.
template <class T>
std::string fmtIntegral(T v, const FmtSpec& sp) {
    char type = sp.hasType ? sp.type : 0;
    if (type == 'f' || type == 'F' || type == 'e' || type == 'E' || type == 'g' ||
        type == 'G' || type == '%')
        return fmtDouble(static_cast<double>(v), sp);

    bool neg = false;
    unsigned long long u = 0;
    if constexpr (std::is_signed_v<T>) {
        long long s = static_cast<long long>(v);
        neg = s < 0;
        u = neg ? static_cast<unsigned long long>(-(s + 1)) + 1ULL
                : static_cast<unsigned long long>(s);
    } else {
        u = static_cast<unsigned long long>(v);
    }

    if (type == 'c') {
        FmtSpec sp2 = sp;
        sp2.type = 0;
        return fmtPad(std::string(1, static_cast<char>(v)), sp2, false);
    }

    char base = (type == 'x' || type == 'X' || type == 'o' || type == 'b') ? type : 'd';
    std::string digits;
    if (base == 'd') {
        digits = std::to_string(u);
    } else if (base == 'x' || base == 'X') {
        char b[64];
        std::snprintf(b, sizeof(b), "%llx", u);
        digits = b;
        if (base == 'X')
            for (auto& c : digits) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    } else if (base == 'o') {
        char b[64];
        std::snprintf(b, sizeof(b), "%llo", u);
        digits = b;
    } else {
        if (u == 0) {
            digits = "0";
        } else {
            unsigned long long t = u;
            while (t) {
                digits += static_cast<char>('0' + (t & 1ULL));
                t >>= 1;
            }
            std::reverse(digits.begin(), digits.end());
        }
    }
    if (sp.sep) digits = fmtGroup(digits, sp.sep);

    std::string prefix;
    if (sp.alt) {
        if (base == 'x') prefix = "0x";
        else if (base == 'X') prefix = "0X";
        else if (base == 'o') prefix = "0o";
        else if (base == 'b') prefix = "0b";
    }
    std::string mag = prefix + digits;
    if (mag.empty()) mag = "0";
    return fmtPad(fmtApplySign(mag, neg, sp), sp, true);
}

inline std::string fmt(double v, const std::string& spec) {
    if (spec.empty()) return str(v);
    return fmtDouble(v, parseFmtSpec(spec));
}

// Everything that is not a plain double (ints, strings, bools, ...).
template <class T>
std::string fmt(const T& v, const std::string& spec) {
    if (spec.empty()) return str(v);
    FmtSpec sp = parseFmtSpec(spec);
    if constexpr (std::is_floating_point_v<T>) {
        return fmtDouble(static_cast<double>(v), sp);
    } else if constexpr (std::is_integral_v<T> && !std::is_same_v<std::remove_cv_t<T>, bool>) {
        return fmtIntegral(v, sp);
    } else {
        std::string body = str(v);
        if (sp.prec >= 0 && static_cast<long long>(body.size()) > sp.prec)
            body = body.substr(0, static_cast<std::size_t>(sp.prec));
        return fmtPad(body, sp, false);
    }
}

// ===================== random / time / math helpers =====================
inline std::mt19937_64& rng() {
    static std::mt19937_64 g(std::random_device{}());
    return g;
}
inline double random() {
    return std::uniform_real_distribution<double>(0.0, 1.0)(rng());
}
inline long long randint(long long a, long long b) {
    if (b < a) throw ValueError("empty range for randrange()");
    return std::uniform_int_distribution<long long>(a, b)(rng());
}
template <class T>
T choice(const std::vector<T>& v) {
    if (v.empty()) throw IndexError("cannot choose from an empty sequence");
    return v[static_cast<std::size_t>(std::uniform_int_distribution<long long>(
        0, static_cast<long long>(v.size()) - 1)(rng()))];
}
template <class T>
void shuffle(std::vector<T>& v) {
    std::shuffle(v.begin(), v.end(), rng());
}

inline long long factorial(long long n) {
    if (n < 0) throw ValueError("factorial() not defined for negative values");
    long long r = 1;
    for (long long i = 2; i <= n; ++i) r *= i;
    return r;
}
inline long long gcd_ll(long long a, long long b) {
    a = a < 0 ? -a : a;
    b = b < 0 ? -b : b;
    while (b) {
        long long t = a % b;
        a = b;
        b = t;
    }
    return a;
}

inline double pi() { return 3.14159265358979323846; }
inline double e() { return 2.71828182845904523536; }
inline double inf() { return std::numeric_limits<double>::infinity(); }

// ---- tuple() --------------------------------------------------------------
// A Python tuple built from a runtime iterable has no static length, so it
// cannot become a std::tuple.  Wrap a vector in a distinct type that prints
// with parentheses and otherwise behaves like a sequence.
template <class T>
struct tup {
    std::vector<T> v;
    using value_type = T;
    std::size_t size() const { return v.size(); }
    bool empty() const { return v.empty(); }
    T& operator[](std::size_t i) { return v[i]; }
    const T& operator[](std::size_t i) const { return v[i]; }
    typename std::vector<T>::iterator begin() { return v.begin(); }
    typename std::vector<T>::iterator end() { return v.end(); }
    typename std::vector<T>::const_iterator begin() const { return v.begin(); }
    typename std::vector<T>::const_iterator end() const { return v.end(); }
};
template <class C>
auto to_tuple(const C& c) {
    tup<elem_t<C>> r;
    for (const auto& e : seq(c)) r.v.push_back(e);
    return r;
}
template <class T>
std::string str(const tup<T>& t) {
    std::string r = "(";
    for (std::size_t i = 0; i < t.v.size(); ++i) {
        if (i) r += ", ";
        r += repr(t.v[i]);
    }
    if (t.v.size() == 1) r += ",";
    return r + ")";
}
template <class T>
std::string repr(const tup<T>& t) {
    return str(t);
}

// Deferred definition of the generic repr: placed here so that it sees every
// str() overload declared above.
template <class T>
std::string repr(const T& v) {
    return str(v);
}

}  // namespace py
// ---- end of py2cpp runtime ------------------------------------------
)PYRT";
